# Generated by Django 5.1.6 on 2025-12-23 00:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0036_alter_bmi_options_alter_headcircumference_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('region', models.CharField(choices=[('world', 'world'), ('europe', 'europe')], max_length=16)),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('last_auth_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwletDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsn', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='owlet.owletaccount')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owlet_devices', to='core.child')),
            ],
        ),
        migrations.CreateModel(
            name='OwletReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('measurement_timestamp_epoch', models.FloatField(blank=True, db_index=True, null=True)),
                ('measurement_timestamp_iso', models.CharField(blank=True, max_length=64, null=True)),
                ('heart_rate_bpm', models.FloatField(blank=True, null=True)),
                ('oxygen_saturation_pct', models.FloatField(blank=True, null=True)),
                ('signal_quality', models.IntegerField(blank=True, null=True)),
                ('movement_baseline', models.IntegerField(blank=True, null=True)),
                ('movement_value', models.IntegerField(blank=True, null=True)),
                ('battery_pct', models.FloatField(blank=True, null=True)),
                ('charging', models.BooleanField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owlet_readings', to='core.child')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='owlet.owletdevice')),
            ],
        ),
        migrations.AddIndex(
            model_name='owletdevice',
            index=models.Index(fields=['account', 'dsn'], name='owlet_owlet_account_87e478_idx'),
        ),
        migrations.AddIndex(
            model_name='owletdevice',
            index=models.Index(fields=['child'], name='owlet_owlet_child_i_c55404_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='owletdevice',
            unique_together={('account', 'dsn')},
        ),
        migrations.AddIndex(
            model_name='owletreading',
            index=models.Index(fields=['device', 'recorded_at'], name='owlet_owlet_device__747595_idx'),
        ),
        migrations.AddIndex(
            model_name='owletreading',
            index=models.Index(fields=['child', 'recorded_at'], name='owlet_owlet_child_i_8b4ed8_idx'),
        ),
        migrations.AddConstraint(
            model_name='owletreading',
            constraint=models.UniqueConstraint(fields=('device', 'measurement_timestamp_epoch'), name='uniq_device_measurement_ts'),
        ),
    ]
